### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by endnch** [functionalCS/curriculum#2]
This link is broken:
https://terrytao.wordpress.com/career-advice/there%E2%80%99s-more-to-mathematics-than-rigour-and-proofs/
It seems like it changed to:
https://terrytao.wordpress.com/career-advice/theres-more-to-mathematics-than-rigour-and-proofs/

**Comment by functionalCS** [comment]
Thanks, I condensed the list of courses and removed it completely in my continuing effort to refine the list to be as minimalist as possible. I will also later add all the labs and hw/solutions/exams for most of the courses like this https://github.com/functionalCS/15150labs
