### ISSUE TITLE
Version with improved typography

### ISSUE THREAD

**Issue by jameskolce** [functionalCS/curriculum#3]
Hi, I found this document a bit hard to read for myself, so I made a fork and improved the typography. I just thought I should let you know in case you wanted to copy some of the changes. I'm not sending a pull request because I saw that the document was written using Org mode so I don't know if I'm breaking something. However, I can send one if you want.

Repository: https://github.com/KolceBackyard/curriculum
Online: https://kolcebackyard.github.io/curriculum/

Thanks for writing this!

**Screenshots for reference (original, original resized and mine):**

---

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/2559808/45399489-77744380-b605-11e8-9f5c-5126c5dd60ff.png">

---

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/2559808/45399518-95da3f00-b605-11e8-86c4-4d38c5d14d7d.png">

---
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/2559808/45399635-10a35a00-b606-11e8-84e0-f43875bca94c.png">

---

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/2559808/45399531-a5f21e80-b605-11e8-93e8-44838dec2b51.png">

---

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/2559808/45399696-48aa9d00-b606-11e8-8c3f-3042e82fe90c.png">

**Comment by functionalCS** [comment]
Yes, it is vasty superior and also what the Road to Common Lisp guide uses http://stevelosh.com/blog/2018/08/a-road-to-common-lisp/ 

I generally keep it vanilla so it can be read on a terminal (which is what I use to update this list, emacs running in termux on a junky android phone) but will eventually change the css. Thanks
